#This file will build test and deploy the project via CICD

variables:
  GIT_STRATEGY: clone

before_script:
  - chmod +x ./gradlew

stages:          # List of stages for jobs, and their order of execution
  - build
  - test
  - deploy

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  tags: 
    - dalfcs_gitlab_docker_ci
  image: gradle:alpine
  script: ./gradlew assemble
  only:
    refs:
      - branches

unit-test-job:   # This job runs in the test stage.
  stage: test    # It only starts when the job in the build stage completes successfully.
  tags:
    - dalfcs_gitlab_docker_ci
  image: gradle:alpine
  script: ./gradlew check
  only:
    refs:
      - branches

deploy-job:      # This job runs in the deploy stage.
  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
  tags: 
    - dalfcs_gitlab_docker_ci
  image: ruby:2.6
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP_NAME --api-key=$HEROKU_API_KEY
  only: 
    - develop